### PR TITLE
Fix incorrect namespace of RendererInterface

### LINKED ISSUE #8: Qferrer\Mjml\Twig\MjmlExtension::__construct() argument issue
I just upgrade my project from Symfony 5.4 to Symfony 6 and i encounter this issue.

```
Qferrer\Mjml\Twig\MjmlExtension::__construct():

Argument #1 ($renderer) must be of type Qferrer\Mjml\Renderer\RendererInterface, 

Qferrer\Mjml\Renderer\BinaryRenderer given
```

My services.yaml:

```yaml
mjml_renderer:
        class: Qferrer\Mjml\Renderer\BinaryRenderer
        arguments:
            - '%kernel.project_dir%/node_modules/.bin/mjml'

    Qferrer\Mjml\Twig\MjmlExtension:
        arguments: ['@mjml_renderer']
        tags: ['twig.extension']
```

UPDATE:
~~But fresh new Symfony 6 project have no issue at all, not sure what is the culprit causing argument type error. Any clue?~~

It is because the current code using `Qferrer\Mjml\Renderer\RendererInterface` but the real namespace is `Qferrer\Mjml\RendererInterface`. PR will be create shortly.

### PR DESCRIPTION
**Pull request by fd6130**
I spotted incorrect namespace for RendererInterface, so i make a PR to correct the issue.

Fix #8

### CODE REVIEW

**Comment by fd6130** [comment]
@qferr I think this is an emergency patch, current version is not usable because of the RendererInterface.

**Comment by qferr** [comment]
Could you fix the namespace in the test classes please? Then, run the tests and tell me that everything is ok? I'll add a CI for the next changes.

**Comment by fd6130** [comment]
Updated. This is my test result:

```
❯ ./vendor/bin/phpunit --testdox tests/Mjml/Twig
PHPUnit 8.5.26 #StandWithUkraine

Mjml Extension (Qferrer\Tests\Mjml\Twig\MjmlExtension)
 ✔ Get filters
 ✔ Render

Time: 39 ms, Memory: 4.00 MB

OK (2 tests, 5 assertions)
```

**Comment by qferr** [comment]
Thank you @fd6130 for your help. I released the patch in v2.0.1.

**Pull request merged**
